imports = [
  "language.go"
]

[[commands]]
package = "go"

[[commands]]
package = "golangci-lint"

[[commands]]
package = "nomad"

[[commands]]
package = "damon"

[[commands]]
package = "vector"

[[commands]]
name = "lint"
command = "fd -e nix -X nixfmt -c"
help = "Run code linters"

[devshell]
name = "nomad-follower"
packages = [
  "diffutils",
  "go",
  "gotools",
  "gopls",
  "gocode",
  "gcc",
  "fd",
  "gnumake",
  "alejandra",
  "nomad-driver-podman",
]
